# Generated by Django 6.0.3 on 2026-03-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='条码')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='货物名称')),
                ('current_station', models.CharField(default='未上线', max_length=100, verbose_name='当前工位')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='扫码工位')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='扫码时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='tracker.item')),
            ],
        ),
    ]
