# Generated by Django 6.0.3 on 2026-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(max_length=50, unique=True, verbose_name='条码前缀')),
                ('target_channel', models.CharField(max_length=50, verbose_name='目标通道')),
            ],
        ),
    ]
