# Generated by Django 6.0.3 on 2026-03-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_routingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_station',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='station_name',
        ),
    ]
