# Generated by Django 6.0.3 on 2026-03-16 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_item_current_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='target_channel',
            field=models.CharField(default='未分流', max_length=100, verbose_name='分流通道'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='tracker.item', verbose_name='关联货物'),
        ),
    ]
