# Generated by Django 6.0.3 on 2026-03-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_scanrecord_target_channel_alter_scanrecord_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_channel',
            field=models.CharField(default='未分流', max_length=100, verbose_name='最近分流通道'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='target_channel',
            field=models.CharField(default='未分流', max_length=100, verbose_name='分流通道'),
        ),
    ]
