# Generated by Django 6.0.3 on 2026-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_item_last_channel_alter_scanrecord_target_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='intended_target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预定目标通道'),
        ),
    ]
