# Generated by Django 6.0.3 on 2026-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_item_created_at_item_status_alter_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_location',
            field=models.CharField(blank=True, default='待定位', max_length=100, verbose_name='当前位置'),
        ),
    ]
