# Generated by Django 6.0.3 on 2026-03-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_item_current_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '货物', 'verbose_name_plural': '货物列表'},
        ),
        migrations.AlterModelOptions(
            name='routingrule',
            options={'verbose_name': '路由规则', 'verbose_name_plural': '路由规则列表'},
        ),
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'verbose_name': '扫码记录', 'verbose_name_plural': '扫码记录列表'},
        ),
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, verbose_name='条码')),
                ('action', models.CharField(max_length=200, verbose_name='操作/状态')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '货物日志',
                'verbose_name_plural': '货物日志列表',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['barcode', '-scanned_at'], name='tracker_ite_barcode_0401df_idx')],
            },
        ),
    ]
