# Generated by Django 6.0.3 on 2026-03-27 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_item_options_alter_routingrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产线名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产线编码')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工位名称')),
                ('station_id', models.CharField(max_length=50, verbose_name='逻辑ID')),
                ('station_type', models.CharField(choices=[('entry', '起点/上线'), ('sorting', '分流/中转'), ('exit', '终点/下线')], max_length=20, verbose_name='工位类型')),
                ('tag_trigger', models.CharField(max_length=255, verbose_name='触发标签路径')),
                ('tag_barcode', models.CharField(max_length=255, verbose_name='条码标签路径')),
                ('tag_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='动作标签路径')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tracker.productionline', verbose_name='所属产线')),
            ],
            options={
                'verbose_name': '工位配置',
                'verbose_name_plural': '工位配置列表',
            },
        ),
    ]
