# Generated by Django 6.0.3 on 2026-03-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_productionline_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tracker.productionline', verbose_name='所属产线'),
        ),
    ]
