# Generated by Django 6.0.3 on 2026-03-30 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_item_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='loc_name_divert',
            field=models.CharField(default='', help_text='如：分流 1', max_length=100, verbose_name='转向后显示的位置'),
        ),
        migrations.AddField(
            model_name='station',
            name='loc_name_pass',
            field=models.CharField(default='', help_text='如：通道 1-2', max_length=100, verbose_name='放行后显示的位置'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tracker.productionline'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('entry', '起点/上线'), ('sorting', '分流/中转'), ('exit', '终点/下线')], max_length=20),
        ),
        migrations.AlterField(
            model_name='station',
            name='tag_action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='动作标签'),
        ),
        migrations.AlterField(
            model_name='station',
            name='tag_barcode',
            field=models.CharField(max_length=255, verbose_name='条码标签'),
        ),
        migrations.AlterField(
            model_name='station',
            name='tag_trigger',
            field=models.CharField(max_length=255, verbose_name='触发标签'),
        ),
    ]
